FROM node:20 as build

WORKDIR /app
COPY . .

RUN npm ci && npm run build

FROM node:20-alpine3.16 as main

COPY --from=build /app /

ENV SUBSTREAMS_API_TOKEN=${SUBSTREAMS_API_TOKEN:-server_none}

EXPOSE 9012

ENTRYPOINT ["node", "dist/bin/cli.js"]
