---
name: Deploy to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/test-substreams-prometheus-sink .
      - name: DockerHub login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Push image to dockerHub
        run: docker push ${{secrets.DOCKER_USER}}/test-substreams-prometheus-sink
